name: Deployment - Reusable Workflow
on:
    workflow_call:
      
jobs:
    reuse-deploy:
        permissions:
            id-token: write
        runs-on: ubuntu-latest
        outputs:
          app_uri: ${{ steps.app-uri.outputs.APP_URI }} 
        environment:
          name: development
          url: https://${{ steps.app-uri.outputs.APP_URI }}
        steps:
            - name: code checkout
              uses: actions/checkout@v4
            
            - name: install kubectl api
              uses: azure/setup-kubectl@v3
            
            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::007670671403:role/github-actions-deploy
                aws-region: us-east-1
            
            - name: update kubeconfig
              run: aws eks update-kubeconfig --region us-east-1 --name cluster-1

            - name: check client version
              run: |
                kubectl version
                echo "======"
            
            - name: save ingress-ip as github variable
              run: | 
                ELB_HOSTNAME=$(kubectl -n ingress-nginx get services ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
                echo "INGRESS_IP=$(nslookup $ELB_HOSTNAME | awk '/^Address: / { print $2 }' | head -n 1)"  >> $GITHUB_ENV

            - name: replace placeholder
              uses: cschleiden/replace-tokens@v1
              with:
                files: '["kubernetes/development/*"]'
              env:
                NAMESPACE: ${{ vars.NAMESPACE }}
                REPLICAS: ${{ vars.REPLICAS }}
                K8S_IMAGE: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
                INGRESS_IP: ${{ env.INGRESS_IP}}

            
            - name: check files
              run: |
                cat kubernetes/development/*.yaml
            
            - name: create secrets
              run: |
                kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
                --from-literal=MONGO_URI=${{env.MONGO_URI}} \
                --from-literal=MONGO_USERNAME=${{ vars.MONGO_USERNAME }} \
                --from-literal=MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
                --save-config \
                --dry-run=client \
                -o yaml | kubectl apply -f -
            
            - name: deploy to Dev
              run: |
                kubectl apply -f kubernetes/development
            
            - name: set app url 
              id: app-uri
              run: echo "APP_URI=$(kubectl get ingress -n  ${{ vars.NAMESPACE }} -o jsonpath='{.items[0].spec.tls[0].hosts[0]}')" >> $GITHUB_OUTPUT